server:
  port: 8090

spring:
  application:
    name: GRADES-SERVICE

  config:
    import: configserver:http://localhost:8096
  profiles:
    active: prod

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8789/eureka
