server:
  port: 8081

spring:
  application:
    name: COURSES-SERVICE
    
  cloud:
    compatibility-verifier:
      enabled: false

  config:
    import: configserver:http://localhost:8085
  profiles:
    active: prod
    
  zipkin:
    base-url: http://localhost:9411
    
  sleuth:
    sampler:
      probability: 1.0

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
