server:
  port: 0
spring:
  application:
    name: enrrollment-service    
  cloud:
    compatibility-verifier:
      enabled: false

  config:
    import: configserver:http://localhost:8085
  profiles:
    active: CONFIG-ENROLLMENT
    
    
  data:
    mongodb:
      host: localhost
      port: 27017
      database: enrollment  
      username: diana
      password: mongo
      authentication-database: admin
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
 
eureka:
    client:
      serviceUrl:
       defaultZone: http://eureka:password@localhost:8761/eureka
         